### ISSUE TITLE
[Security] Dependencies security vulnerabilities

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/docs-and-discussions#8]
@Holger-Will The bot that is now in place to scan for dependency vulnerabilities seem to scan not only direct dependencies but also dependencies of dependencies (`acorn` & `minimist` in that case, which are not directly part of our dependencies).

Is it ok to have a bot updating those sub dependencies and taking the risk to break our main dependencies instead of watching only for outdated direct dependencies?

**Note:** I merged the auto pull requests for `acorn` before I realized that `acorn` was not part of our direct dependencies so we may reverse this if the behavior isn't what you were expecting :-)

**Comment by alexlemaire** [comment]
Pulling here answer from Hangout:
> yes that is actually the purpose of that bot... you do not want to manually check all depenedencies of dependencies...

Closing this now!

**Comment by alexlemaire** [comment]
@Holger-Will 

**I updated all the dependencies I could to fix the security notifications.** Some failure points still remain unfortunately because some dependencies did not update their own dependencies...

**Details:**
- _elements_ (`Prototype pollution` vulnerability): `karma` and its various modules are the weak point still. `karma-coverage` for example uses `istanbul` which has been replaced by `nyc` now so it uses an outdated version of `minimist`. Same goes for `karma-mocha` and `karma` itself which use an old version of `minimist`
- _serverless_: `serverless` currently has [high security issue](https://www.npmjs.com/advisories/1217). This seems to be worked on (see [here](https://github.com/serverless/serverless/issues/7402)) but for now no fix in place unfortunately...
- _wemalo-layer_: **for this one I'll need your support.** `wemalo-layer` relies on `wemalo-api-wrapper` (the wrapper you developed and published) which relies on dependencies with older `minimist` version. You should be able to fix this when migrating all dependencies to latest version I think.

**Comment by Holger-Will** [comment]
nyc is the cli of instanbul... so  htey basically use an old version of instanbul still... how did you try to update?
have you checked thier repos if there are issues filed against them? if not, you can file it there... but make sure you really install the latest version...
i will take care about wemalo-api-wrapper...

**Comment by Holger-Will** [comment]
new version of `wemalo-api-wrapper` up and running... update to version 0.0.5

**Comment by Holger-Will** [comment]
so it's basically 

```
npm update
npm ls | grep minimist
```
and check ist minimist is now > 1.2.2

**Comment by Holger-Will** [comment]
karma-coverage seems to have a fix in 2.0.1

**Comment by Holger-Will** [comment]
https://github.com/karma-runner/karma/issues/3447

**Comment by Holger-Will** [comment]
as stated in the issue at `karma`, we only have serverless as dev-dependency, the risk of actually being attacked is quite low...

**Comment by alexlemaire** [comment]
> new version of `wemalo-api-wrapper` up and running... update to version 0.0.5

Update done!

> there is already a PR waiting for approval

Alright I guess we wait for Karma to be updated and then we can upgrade to the latest version to fix the issue.

> as stated in the issue at karma, we only have serverless as dev-dependency, the risk of actually being attacked is quite low...

`serverless` is only a problem for me in `action-slscli` as it's used as regular dependency. But the update is also in progress so hopefully I can upgrade to the latest `serverless` version soon

Since it's running as an action I'd say the only risk is for the instance running this action. So it probably harms more GitHub than us in the end... (not that it makes it better)

> nyc is the cli of instanbul... so they basically use an old version of instanbul still... how did you try to update?

I don't have the warning message in my head anymore but I got feedback from `npm` while running `npm i -D karma@latest` (and all the karma related modules) that `istanbul` had been deprecated and isn't maintained anymore. So I'm reporting it back here to discuss and see what we can do :+1:

I thought `nyc` was some kind of improvement made upon `istanbul`, my bad!

**Comment by alexlemaire** [comment]
Closing this now
